run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
  skip-files:
    - ".*_generated.go"

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - gocritic
    - revive
    - unused
    - ineffassign
    - gosimple
    - misspell
  disable:
    # 無効化したいものはここに追加
    # - errcheck
    # - gocyclo

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: RSS-Summaries
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-same-issues: 50
  max-issues-per-linter: 0
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019" # Deprecated警告を一時的に除外したい場合

output:
  formats:
    - format: line-number
