name: Job

on:
  push:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Tests with Coverage
        run: |
          make -f scripts/Makefile test
          make -f scripts/Makefile cover

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Security check
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
