name: Pushed

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Coverage
        run: |
          make -f scripts/Makefile cover

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy coverage.html
        run: |
          mkdir -p public
          cp coverage.html public/
          echo "coverage.html deployed to GitHub Pages"

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1