name: Lint and Security Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install reviewdog
        run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest

      - name: Run golangci-lint with reviewdog
        run: |
          golangci-lint run --config .golangci.yml ./... \
            | reviewdog -f=golangci-lint \
              -name="golangci-lint" \
              -reporter=github-pr-review \
              -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run govulncheck with reviewdog
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./... 2>&1 | reviewdog -efm="%f:%l:%c: %m" \
            -name="govulncheck" \
            -reporter=github-pr-review \
            -fail-on-error=false
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
